# CodeContext Configuration
version: "2.0"

# Virtual Graph Engine Settings
virtual_graph:
  enabled: true
  batch_threshold: 5
  batch_timeout: 500ms
  max_shadow_memory: 100MB
  diff_algorithm: myers

# Incremental Update Settings
incremental_update:
  enabled: true
  min_change_size: 10
  max_patch_history: 1000
  compact_patches: true

# Language Configuration
languages:
  typescript:
    extensions: [".ts", ".tsx", ".mts", ".cts"]
    parser: "tree-sitter-typescript"
  javascript:
    extensions: [".js", ".jsx", ".mjs", ".cjs"]
    parser: "tree-sitter-javascript"
  python:
    extensions: [".py", ".pyi"]
    parser: "tree-sitter-python"
  go:
    extensions: [".go"]
    parser: "tree-sitter-go"
  dart:
    extensions: [".dart"]
    parser: "tree-sitter-dart"

# Compact Profiles
compact_profiles:
  minimal:
    token_target: 0.3
    preserve: ["core", "api", "critical"]
    remove: ["tests", "examples", "generated"]
  balanced:
    token_target: 0.6
    preserve: ["core", "api", "types", "interfaces"]
    remove: ["tests", "examples"]
  aggressive:
    token_target: 0.15
    preserve: ["core", "api"]
    remove: ["tests", "examples", "generated", "comments"]
  debugging:
    preserve: ["error_handling", "logging", "state"]
    expand: ["call_stack", "dependencies"]
  documentation:
    preserve: ["comments", "types", "interfaces"]
    remove: ["implementation_details", "private_methods"]

# Output Settings
output:
  format: "markdown"
  template: "default"
  include_metrics: true
  include_toc: true

# File Patterns
include_patterns:
  - "**/*.ts"
  - "**/*.tsx"
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.py"
  - "**/*.go"
  - "**/*.dart"

# Use built-in exclude patterns for common directories/files that are typically
# not useful for code analysis (node_modules, .git, build outputs, etc.)
# Set to false to disable all default excludes and use only your patterns
use_default_excludes: true

# Additional patterns to exclude (merged with defaults if use_default_excludes is true)
# Use ! prefix to explicitly include files that would otherwise be excluded
exclude_patterns:
  # Additional excludes
  - "docs/**"
  - "*.min.js"
  - "*.min.css"

  # Dart/Flutter excludes
  - ".dart_tool/**"
  - "build/**"
  - "*.g.dart"
  - "*.freezed.dart"
  - "*.mocks.dart"
  
  # Example: Include specific files that would normally be excluded
  # - "!node_modules/my-local-package/**"
  # - "!vendor/our-company/**"
  # - "!.github/workflows/ci.yml"

# Default exclude patterns (when use_default_excludes is true):
# Build outputs: dist/**, build/**, out/**, target/**, bin/**, obj/**
# Dependencies: node_modules/**, vendor/**, packages/**, bower_components/**
# Python: __pycache__/**, *.py[cod], .venv/**, venv/**, env/**, .tox/**
# Dart/Flutter: .dart_tool/**, build/**, *.g.dart, *.freezed.dart
# Testing: coverage/**, .nyc_output/**, test-results/**, htmlcov/**
# IDE/Tools: .idea/**, .vscode/**, *.swp, .DS_Store, Thumbs.db
# VCS: .git/**, .svn/**, .hg/**
# Temp: *.log, logs/**, tmp/**, temp/**, *.tmp, *.bak
# Other: .cache/**, .next/**, .nuxt/**, .pytest_cache/**, .terraform/**
