extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
  indentation:
    indent-sequences: consistent
    spaces: 2
  truthy:
    level: warning
  comments:
    require-starting-space: true
  document-start:
    present: false

