site_name: PyInj
site_description: Type-safe dependency injection for Python 3.13+
site_url: https://qriusglobal.github.io/pyinj/
repo_url: https://github.com/QriusGlobal/pyinj
repo_name: QriusGlobal/pyinj
copyright: Copyright © Qrius Global

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Type Safety: type-safety.md
  - Usage: usage.md
  - Advanced: advanced.md
  - Testing: testing.md
  - Performance: performance.md
  - Troubleshooting: troubleshooting.md
  - API: api.md
  - LLM Guide (Raw): llm-raw.md
  - Contributing: contributing.md
  - Release Process: releases.md

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/QriusGlobal/pyinj
  version:
    provider: mike
    default: latest

plugins:
  - search
  - llmstxt:
      markdown_description: "PyInj is a lightweight, type-safe dependency injection container for Python 3.13+, designed for modern applications with O(1) lookup performance and zero external dependencies."
      full_output: llms-full.txt
      sections:
        Core Documentation:
          - index.md: "Overview and introduction to PyInj"
          - getting-started.md: "Quick start guide"
          - type-safety.md: "Type safety features and patterns"
          - usage.md: "Usage patterns and examples"
        Advanced Topics:
          - advanced.md: "Advanced patterns and techniques"
          - testing.md: "Testing with PyInj"
          - performance.md: "Performance considerations"
          - troubleshooting.md: "Common issues and solutions"
        Reference:
          - api.md: "API reference"
          - llm.md: "LLM integration guide"
          - llm-raw.md: "Raw documentation access"
        Contributing:
          - contributing.md: "Contribution guidelines"
          - releases.md: "Release process"

# Hook to copy extra files
hooks:
  - scripts/copy_extra_files.py

# Additional JavaScript and CSS for LLM tools
extra_javascript:
  - javascripts/llm-tools.js

extra_css:
  - stylesheets/llm-tools.css
