site_name: PyInj
site_description: Type-safe dependency injection for Python 3.13+
site_url: https://qriusglobal.github.io/pyinj/
repo_url: https://github.com/QriusGlobal/pyinj
repo_name: QriusGlobal/pyinj
copyright: Copyright © Qrius Global

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Type Safety: type-safety.md
  - Usage: usage.md
  - Advanced: advanced.md
  - Testing: testing.md
  - Performance: performance.md
  - Troubleshooting: troubleshooting.md
  - API: api.md
  - LLM Guide (Raw): llm-raw.md
  - Contributing: contributing.md
  - Release Process: releases.md

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/QriusGlobal/pyinj
  version:
    provider: mike
    default: latest

plugins:
  - search

# Hook to copy extra files
hooks:
  - scripts/copy_extra_files.py
