name: Bug report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue!

        Before reporting, please search through [existing issues](https://github.com/QriusGlobal/injx/issues?q=is:issue+is:open+label:bug).

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: |
        Provide a minimal code example that demonstrates the issue.
        This helps us understand and fix the problem quickly.
      render: python
      placeholder: |
        from injx import Container, Token

        # Your code that reproduces the issue
    validations:
      required: true

  - type: input
    attributes:
      label: Injx Version
      description: |
        Output of: `python -c "import injx; print(injx.__version__)"`
      placeholder: e.g., 0.2.0
    validations:
      required: true

  - type: input
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: e.g., Python 3.13.0
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System
      description: Your OS and version
      placeholder: e.g., Ubuntu 22.04, macOS 14.0, Windows 11

  - type: textarea
    attributes:
      label: Error Output
      description: |
        If applicable, paste the full error message/traceback
      render: python
      placeholder: |
        Traceback (most recent call last):
          ...

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem
