blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/QriusGlobal/injx/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
  - name: Security Issue
    url: https://github.com/QriusGlobal/injx/security/advisories
    about: Report security vulnerabilities privately
