name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install project (dev)
        run: |
          uv sync --dev

      - name: Run tests
        run: |
          uv run pytest -q

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install docs dependencies
        run: |
          uv pip install mkdocs-material mkdocs-minify-plugin

      - name: Build docs
        run: |
          uv run mkdocs build --strict
