name: Docs Versioned Release

on:
  release:
    types: [published]

jobs:
  versioned-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.13'

      - name: Install docs tooling
        run: |
          uv pip install mkdocs-material mkdocs-minify-plugin mkdocstrings[python] mike

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy versioned docs and update 'latest'
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          VERSION="${TAG#v}"
          echo "Deploying docs for version $VERSION"
          uv run mike deploy --push --branch gh-pages --update-aliases "$VERSION" latest

