name: Docs

'on':
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791  # v4.1.0
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@3b9817b1bf26186f03ab8277bab9b827ea5cc254  # v6.0.0
        with:
          python-version: '3.13'
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          activate-environment: true

      - name: Install docs tooling
        run: |
          uv pip install mkdocs-material mkdocs-minify-plugin mkdocstrings[python] mike mkdocs-llmstxt beautifulsoup4 html2text

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy dev docs to 'next'
        run: |
          uv run mike deploy --push --branch gh-pages next
