name: Publish to PyPI (Trusted Publishing)

'on':
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # required for OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # For releases, build exactly the tagged ref; for manual runs, use the current sha
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.sha }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          activate-environment: true

      - name: Build
        run: |
          rm -rf dist
          uv build

      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
